## Домашнее задание к уроку "Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ."

In [1]:
import numpy as np
import pandas as pd
from scipy.stats import norm, t as student
from math import sqrt

In [2]:
# ковариация
def my_cov(x, y):
    return np.mean(x * y) - np.mean(x) * np.mean(y)

In [3]:
# коэффициент корреляции Пирсона
def my_r(x, y):
    return my_cov(x, y) / (np.std(x, ddof=0) * np.std(y, ddof=0))

In [4]:
# доверительный интервал
def confidence_interval(mean, norm_value, std, n):
    return mean - norm_value * std/sqrt(n), mean + norm_value * std/sqrt(n)

**1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):  
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],  
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].  
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy.  
Полученные значения должны быть равны.  
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.**

In [5]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [7]:
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [8]:
# ковариация по формуле
round(my_cov(zp, ks), 2)

9157.84

In [9]:
# ковариация с использованием модуля numpy
np.cov(zp, ks, ddof=0)[0, 1]

9157.84

In [10]:
# коэффициент корреляции Пирсона по формуле
my_r(zp, ks)

0.8874900920739158

In [11]:
zp_, ks_ = pd.Series(zp), pd.Series(ks)

In [12]:
# коэффициент корреляции Пирсона с использованием модуля numpy
np.corrcoef(zp_, ks_)[0, 1]

0.8874900920739162

In [13]:
# коэффициент Пирсона показывает высокую связь между значениями величины заработной платы заемщиков банка (zp) и 
# значениями их поведенческого кредитного скоринга (ks)

**2) Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:  
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.  
Известно, что в генеральной совокупности IQ распределен нормально.  
Найдите доверительный интервал для математического ожидания с надежностью 0.95.**

In [14]:
x = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
x

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [15]:
n = x.shape[0]
n

10

In [16]:
p = 0.95

In [17]:
# оценка среднего арифметического
a = np.mean(x)
a

118.1

In [18]:
# среднее квадратичное отклонение выборки
std = np.std(x, ddof=1)
std

10.54566788359614

In [19]:
# уровень значимости
α = round(1 - p, 2)
α

0.05

In [20]:
# генеральная совокупность распределена нормально, среднее квадратичное отклонение генеральной совокупности 
# неизвестно, значит, берём t-критерий

In [21]:
# количество степеней свободы для поиска
v = n - 1
v

9

In [22]:
t = student.ppf((1 + p)/2, v)
t

2.2621571627409915

In [23]:
# доверительный интервал для математического ожидания с надежностью 0,95
confidence_interval(a, t, std, n)

(110.55608365158724, 125.64391634841274)

**3) Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2.  
Найдите доверительный интервал для математического
ожидания с надежностью 0.95.**

In [24]:
D = 25
n = 27
a = 174.2
p = 0.95

In [25]:
# среднее квадратичное отклонение генеральной совокупности
std = sqrt(D)
std

5.0

In [26]:
# уровень значимости
α = round(1 - p, 2)
α

0.05

In [27]:
# генеральная совокупность распределена нормально,среднее квадратичное отклонение генеральной совокупности 
# известно (дисперсия известна), значит, берём z-критерий

In [28]:
z = norm.ppf((1 + p)/2)
z

1.959963984540054

In [29]:
# доверительный интервал для математического ожидания с надежностью 0.95
confidence_interval(a, z, std, n)

(172.3140237765397, 176.08597622346028)