## Домашнее задание к уроку "Урок 8. Дисперсионный анализ. Логистическая регрессия"

In [1]:
import numpy as np
from scipy import stats

**1\. Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов.  
Даны значения роста в трех группах случайно выбранных спортсменов:  
Футболисты: 173, 175, 180, 178, 177, 185, 183, 182.  
Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180.  
Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.**

In [2]:
# проведем однофакторный дисперсионный анализ
# предполагаем, что рост распределён нормально, дисперсии однородны, распределения наблюдений не связаны между собой
# количественный признак - средний рост - зависит (или не зависит) от качественного фактора - вида спорта:
# гипотеза H0: μ1 = μ2 = μ3
# гипотеза H1: μ1 != μ2 != μ3
# возьмём уровень значимости α = 0.05

In [3]:
# выборка для футболистов
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y1

array([173, 175, 180, 178, 177, 185, 183, 182])

In [4]:
# выборка для хоккеистов
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y2

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [5]:
# выборка для штангистов
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
y3

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [6]:
# количесвто выборок
k = 3

In [7]:
# количество элементов первой выборки
n1 = y1.shape[0]
n1

8

In [8]:
# количество элементов второй выборки
n2 = y2.shape[0]
n2

9

In [9]:
# количество элементов третьей выборки
n3 = y3.shape[0]
n3

11

In [10]:
# общее количество элементов
n = n1 + n2 + n3
n

28

In [11]:
# среднее значение по первой выборке
y1_mean = np.mean(y1)
y1_mean

179.125

In [12]:
# среднее значение по второй выборке
y2_mean = np.mean(y2)
y2_mean

178.66666666666666

In [13]:
# среднее значение по третьей выборке
y3_mean = np.mean(y3)
y3_mean

172.72727272727272

In [14]:
# видно, что средний рост по группам разнится
# установим, что это отличие статистически значимо

In [15]:
# все элементы выборок
y_all = np.concatenate([y1, y2, y3])
y_all

array([173, 175, 180, 178, 177, 185, 183, 182, 177, 179, 180, 188, 177,
       172, 171, 184, 180, 172, 173, 169, 177, 166, 180, 178, 177, 172,
       166, 170])

In [16]:
# среднее значение по всем элементам выборок
y_mean = np.mean(y_all)
y_mean

176.46428571428572

In [17]:
# сумма квадратов отклонений наблюдений от общего стреднего
s2 = np.sum((y_all - y_mean)**2)
s2

830.9642857142854

In [18]:
# сумма квадратов отклонений средних групповых значений от общего среднего
s2_f = ((y1_mean - y_mean)**2) * n1 + ((y2_mean - y_mean)**2) * n2 + ((y3_mean - y_mean)**2) * n3
s2_f

253.9074675324678

In [19]:
# остаточная сумма квадратов отклонений
s2_residual = np.sum((y1 - y1_mean)**2) + np.sum((y2 - y2_mean)**2) + np.sum((y3 - y3_mean)**2)
s2_residual

577.0568181818182

In [20]:
s2

830.9642857142854

In [21]:
s2_all = s2_f + s2_residual
s2_all

830.964285714286

In [22]:
# значения должны быть равны
round(s2, 11) == round(s2_all, 11)

True

In [23]:
# общая дисперсия
sigma2_general = s2 / (n - 1)
sigma2_general

30.776455026455015

In [24]:
# фактическая (объясненная) дисперсия
sigma2_f = s2_f / (k - 1)
sigma2_f

126.9537337662339

In [25]:
# остаточная (необъясненная) дисперсия
sigma2_residual = s2_residual / (n - k)
sigma2_residual

23.08227272727273

In [26]:
# расчитанный критерий Фишера
F_observed = sigma2_f / sigma2_residual
F_observed

5.500053450812598

In [27]:
# уровень значимости
α = 0.05
α

0.05

In [28]:
# число степеней свободы числителя
v1 = k - 1
v1

2

In [29]:
# число степеней свободы знаменателя
v2 = n - k
v2

25

In [30]:
# табличное значение критерия Фишера для α = 0.05
F = 3.38

In [31]:
F_observed > F

True

In [32]:
# расчёт с помощью модуля stats
stats.f_oneway(y1, y2, y3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

In [33]:
# pvalue < α, наблюдаемый критерий Фишера больше табличного - различия среднего роста среди взрослых футболистов, 
# хоккеистов и штангистов есть, то есть вид спорта влияет на средний рост на уровне значимости α = 0.05
# различие среднего роста в трех группах статистически значимо на уровне α = 0.05